@startuml High Level

skinparam ConditionStyle bold
skinparam activity {
  StartColor green
  BarColor SaddleBrown
  EndColor red
  BackgroundColor WhiteSmoke
  BorderColor Black
  FontName Arial
}

(*) --> "Recepcion de la solicitud"
--> if "Evaluacion de la solicitud" then

  -down->[Requiere procesamiento en las máquinas] "Almacenamiento de la solicitud" 
  --> "Envio de la solicitud hacia las máquinas"
  --> Extracción de información relacionada
  --> "Preparación de la respuesta a devolver"

else

  -right->[No requiere procesamiento en las maquinas] "Extracción de la información solicitada" 
  --> "Preparación de la respuesta a devolver"

endif


--> (*)
@enduml
