@startuml Order
skinparam ConditionStyle bold
skinparam activity {
  StartColor green
  BarColor SaddleBrown
  EndColor red
  BackgroundColor WhiteSmoke
  BorderColor Black
  FontName Arial
}

start
:Creacion de la solicitud de producción de una orden;
:Almacenamiento de la solicitud;
:Envio de la orden a Step7 para que este coordine la ejecución con las máquinas;
:Extraccion de informacion relacionada con la orden;
:Preparacion de la respuesta a devolver;
stop
@enduml