@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "co.edu.javeriana.ctai.installer.model.tools.Tools#runCmdCommand(String)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": false,
    "cutTests": true,
    "cutClient": false,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": false,
    "cutConstructors": false
  },
  "graphTraversal": {
    "forwardDepth": 2,
    "backwardDepth": 2,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": true,
    "showMethodParametersNames": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showCallOrder": true,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": true
  },
  "rootClass": "co.edu.javeriana.ctai.installer.model.tools.Tools",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_100278 { 
   	label=edu
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_496592481 { 
   	label=javeriana
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_108133415 { 
   	label=Tools
	labeljust=l
	fillcolor=white
	style=filled
   
   Tools861186420XXXfrontExE949967062[
	label="+ frontExE(osName: String, mainDirectory: Path): boolean"
	style=filled
	fillcolor=white
	tooltip="Tools

null"
	fontcolor=darkgreen
];

Tools861186420XXXrunCmdCommand1808118735[
	label="+ runCmdCommand(command: String)"
	style=filled
	fillcolor=white
	tooltip="Tools

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_1795875308 { 
   	label=Install
	labeljust=l
	fillcolor=white
	style=filled
   
   Install1071375199XXXkillFrond0[
	label="+ killFrond()"
	style=filled
	fillcolor=white
	tooltip="Install

null"
	fontcolor=darkgreen
];

Install1071375199XXXnavExE0[
	label="+ navExE()"
	style=filled
	fillcolor=white
	tooltip="Install

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
Install1071375199XXXkillFrond0 -> Tools861186420XXXrunCmdCommand1808118735[label=13];
Install1071375199XXXnavExE0 -> Tools861186420XXXfrontExE949967062[label=0];
Tools861186420XXXfrontExE949967062 -> Tools861186420XXXrunCmdCommand1808118735[label=11];
Tools861186420XXXfrontExE949967062 -> Tools861186420XXXrunCmdCommand1808118735[label=7];
    
}
@enduml