@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "co.edu.javeriana.ctai.installer.model.tools.Tools#getLoggingService()",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": false,
    "cutTests": true,
    "cutClient": false,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": false,
    "cutConstructors": false
  },
  "graphTraversal": {
    "forwardDepth": 2,
    "backwardDepth": 2,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": true,
    "showMethodParametersNames": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showCallOrder": true,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": true
  },
  "rootClass": "co.edu.javeriana.ctai.installer.model.tools.Tools",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_100278 { 
   	label=edu
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_496592481 { 
   	label=javeriana
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_108133415 { 
   	label=Tools
	labeljust=l
	fillcolor=white
	style=filled
   
   Tools861186420XXXgetLoggingService0[
	label="+ getLoggingService(): LoggingService"
	style=filled
	fillcolor=white
	tooltip="Tools

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_1795875308 { 
   	label=Install
	labeljust=l
	fillcolor=white
	style=filled
   
   Install1071375199XXXInstall0[
	label="+ Install()"
	style=filled
	fillcolor=white
	tooltip="Install

null"
	fontcolor=darkgreen
];

Install1071375199XXXexecSecurityModule0[
	label="+ execSecurityModule()"
	style=filled
	fillcolor=white
	tooltip="Install

null"
	fontcolor=darkgreen
];

Install1071375199XXXexitFronEndPID0[
	label="+ exitFronEndPID()"
	style=filled
	fillcolor=white
	tooltip="Install

null"
	fontcolor=darkgreen
];

Install1071375199XXXgetInstance0[
	label="+ getInstance(): Install"
	style=filled
	fillcolor=white
	tooltip="Install

null"
	fontcolor=darkgreen
];

Install1071375199XXXkillFrond0[
	label="+ killFrond()"
	style=filled
	fillcolor=white
	tooltip="Install

null"
	fontcolor=darkgreen
];

Install1071375199XXXnavExE0[
	label="+ navExE()"
	style=filled
	fillcolor=white
	tooltip="Install

null"
	fontcolor=darkgreen
];

Install1071375199XXXrunTgfestoModule0[
	label="+ runTgfestoModule()"
	style=filled
	fillcolor=white
	tooltip="Install

null"
	fontcolor=darkgreen
];

Install1071375199XXXsetMvnwCommand0[
	label="+ setMvnwCommand()"
	style=filled
	fillcolor=white
	tooltip="Install

null"
	fontcolor=darkgreen
];

Install1071375199XXXstopOlds1808118735[
	label="+ stopOlds(processName: String)"
	style=filled
	fillcolor=white
	tooltip="Install

null"
	fontcolor=darkgreen
];

Install1071375199XXXstopProcesses0[
	label="+ stopProcesses()"
	style=filled
	fillcolor=white
	tooltip="Install

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
Install1071375199XXXInstall0 -> Install1071375199XXXsetMvnwCommand0[label=11];
Install1071375199XXXInstall0 -> Tools861186420XXXgetLoggingService0[label=2];
Install1071375199XXXInstall0 -> Tools861186420XXXgetLoggingService0[label=7];
Install1071375199XXXexecSecurityModule0 -> Tools861186420XXXgetLoggingService0[label=14];
Install1071375199XXXexecSecurityModule0 -> Tools861186420XXXgetLoggingService0[label=18];
Install1071375199XXXexecSecurityModule0 -> Tools861186420XXXgetLoggingService0[label=20];
Install1071375199XXXexecSecurityModule0 -> Tools861186420XXXgetLoggingService0[label=25];
Install1071375199XXXexecSecurityModule0 -> Tools861186420XXXgetLoggingService0[label=7];
Install1071375199XXXexitFronEndPID0 -> Tools861186420XXXgetLoggingService0[label=10];
Install1071375199XXXexitFronEndPID0 -> Tools861186420XXXgetLoggingService0[label=7];
Install1071375199XXXgetInstance0 -> Install1071375199XXXInstall0[label=0];
Install1071375199XXXkillFrond0 -> Tools861186420XXXgetLoggingService0[label=11];
Install1071375199XXXkillFrond0 -> Tools861186420XXXgetLoggingService0[label=15];
Install1071375199XXXkillFrond0 -> Tools861186420XXXgetLoggingService0[label=17];
Install1071375199XXXnavExE0 -> Tools861186420XXXgetLoggingService0[label=11];
Install1071375199XXXnavExE0 -> Tools861186420XXXgetLoggingService0[label=2];
Install1071375199XXXnavExE0 -> Tools861186420XXXgetLoggingService0[label=9];
Install1071375199XXXrunTgfestoModule0 -> Tools861186420XXXgetLoggingService0[label=13];
Install1071375199XXXrunTgfestoModule0 -> Tools861186420XXXgetLoggingService0[label=17];
Install1071375199XXXrunTgfestoModule0 -> Tools861186420XXXgetLoggingService0[label=19];
Install1071375199XXXrunTgfestoModule0 -> Tools861186420XXXgetLoggingService0[label=24];
Install1071375199XXXsetMvnwCommand0 -> Tools861186420XXXgetLoggingService0[label=2];
Install1071375199XXXsetMvnwCommand0 -> Tools861186420XXXgetLoggingService0[label=7];
Install1071375199XXXsetMvnwCommand0 -> Tools861186420XXXgetLoggingService0[label=9];
Install1071375199XXXstopOlds1808118735 -> Install1071375199XXXstopProcesses0[label=11];
Install1071375199XXXstopOlds1808118735 -> Install1071375199XXXstopProcesses0[label=16];
Install1071375199XXXstopOlds1808118735 -> Tools861186420XXXgetLoggingService0[label=13];
Install1071375199XXXstopOlds1808118735 -> Tools861186420XXXgetLoggingService0[label=18];
Install1071375199XXXstopProcesses0 -> Tools861186420XXXgetLoggingService0[label=11];
Install1071375199XXXstopProcesses0 -> Tools861186420XXXgetLoggingService0[label=18];
Install1071375199XXXstopProcesses0 -> Tools861186420XXXgetLoggingService0[label=21];
Install1071375199XXXstopProcesses0 -> Tools861186420XXXgetLoggingService0[label=29];
Install1071375199XXXstopProcesses0 -> Tools861186420XXXgetLoggingService0[label=31];
Install1071375199XXXstopProcesses0 -> Tools861186420XXXgetLoggingService0[label=39];
Install1071375199XXXstopProcesses0 -> Tools861186420XXXgetLoggingService0[label=41];
Install1071375199XXXstopProcesses0 -> Tools861186420XXXgetLoggingService0[label=8];
    
}
@enduml