
# Configuracion del servidor
server:
  port: ${SERVER_PORT:8080}

# Configuracion de Spring
spring:
  # Configuración de Spring JPA
  jpa:
    generate-ddl: false
    # Propiedades de Spring JPA
    properties:
      # Propiedades de Hibernate
      hibernate:
        dialect: net.ucanaccess.hibernate.dialect.UCanAccessDialect
        globally_quoted_identifiers: true
        temp:
          use_jdbc_metadata_defaults: false
        hbm2ddl:
          auto: none
    # Configuración de Hibernate
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
