@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "co.edu.javeriana.ctai.tgsecurity.controller.web.users.PostController",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_100278 { 
   	label=edu
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_496592481 { 
   	label=javeriana
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   ClientServiceImp2047046643[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ClientServiceImp</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   clientRepository: IClientRepository [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ existsByCedula(cedula: Long): Boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ existsByCelular(celular: Long): Boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ existsByCorreoElectronico(correo: String): Boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ findAll(): List&lt;Cliente&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ findByCedula(cedula: Long): Cliente</TD></TR>
<TR><TD ALIGN="LEFT" >+ findByUsuario(usuario: User): Cliente</TD></TR>
<TR><TD ALIGN="LEFT" >+ save(cliente: Cliente): Cliente</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Cliente489267886[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Cliente</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   apellido: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   celular: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   correoElectronico: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   identificacion: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   nombre: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   orders: List&lt;Order&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   rol: Rol [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   usuario: User [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Order2119090516[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Order</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   cliente: Cliente [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: long [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id_part: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id_workPlan: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   image_filePath: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   orderNumber: long [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   title: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

OrderProcessingService425788027[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)OrderProcessingService</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   orderNumber: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   orderQueue: ConcurrentLinkedQueue&lt;Order&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   orderRepository: IOrderRepository [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   restTemplate: RestTemplate [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ enqueueOrder(order: Order)</TD></TR>
<TR><TD ALIGN="LEFT" >- processOrders()</TD></TR>
<TR><TD ALIGN="LEFT" >- sendHttpRequest(order: Order): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ startProcessing()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

PostController1649190291[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)PostController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   clientService: IClientService [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   orderProcessingService: OrderProcessingService [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ saveOrder(orderRequest: OrderRequest): ResponseEntity&lt;OrderRequest&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
Order2119090516 -> Cliente489267886[label="cliente
[0..1]"];
OrderProcessingService425788027 -> Order2119090516[label="orderQueue
[0..*]"];
PostController1649190291 -> ClientServiceImp2047046643[arrowhead=none];
PostController1649190291 -> OrderProcessingService425788027[label="orderProcessingService
[1]"];
    
}
@enduml