@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "co.edu.javeriana.ctai.tgsecurity.controller.web.users.PostController#saveOrder(OrderRequest)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "co.edu.javeriana.ctai.tgsecurity.controller.web.users.PostController",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_100278 { 
   	label=edu
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_496592481 { 
   	label=javeriana
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_143101955 { 
   	label=ClientServiceImp
	labeljust=l
	fillcolor=white
	style=filled
   
   ClientServiceImp1642994765XXXexistsByCedula2374300[
	label="+ existsByCedula()"
	style=filled
	fillcolor=white
	tooltip="ClientServiceImp

null"
	fontcolor=darkgreen
];

ClientServiceImp1642994765XXXfindByCedula2374300[
	label="+ findByCedula()"
	style=filled
	fillcolor=white
	tooltip="ClientServiceImp

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1975621175 { 
   	label=PostController
	labeljust=l
	fillcolor=white
	style=filled
   
   PostController1649190291XXXsaveOrder2144918655[
	label="+ saveOrder()"
	style=filled
	fillcolor=white
	tooltip="PostController

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_712563582 { 
   	label=OrderProcessingService
	labeljust=l
	fillcolor=white
	style=filled
   
   OrderProcessingService988843964XXXenqueueOrder76453678[
	label="+ enqueueOrder()"
	style=filled
	fillcolor=white
	tooltip="OrderProcessingService

&#10;  Agrega una orden a la cola de procesamiento.&#10; &#10;  @param order La orden a encolar.&#10; "
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
PostController1649190291XXXsaveOrder2144918655 -> ClientServiceImp1642994765XXXexistsByCedula2374300;
PostController1649190291XXXsaveOrder2144918655 -> ClientServiceImp1642994765XXXfindByCedula2374300;
PostController1649190291XXXsaveOrder2144918655 -> OrderProcessingService988843964XXXenqueueOrder76453678;
    
}
@enduml