@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "src/main/java/co/edu/javeriana/ctai/installer/model/tools",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": false,
    "cutTests": true,
    "cutClient": false,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": false
  },
  "graphTraversal": {
    "forwardDepth": 2,
    "backwardDepth": 2,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "co.edu.javeriana.ctai.installer.model.Install",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_100278 { 
   	label=edu
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_496592481 { 
   	label=javeriana
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   Install1071375199[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Install</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   mainDirectory: Path [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   mes4DDBBpath: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   mvnwCommand: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   osName: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   pidTgFesto: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   pidTgSecurity: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   tools: Tools [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ Install()</TD></TR>
<TR><TD ALIGN="LEFT" >+ execSecurityModule()</TD></TR>
<TR><TD ALIGN="LEFT" >+ exitFronEndPID()</TD></TR>
<TR><TD ALIGN="LEFT" >+ killFrond()</TD></TR>
<TR><TD ALIGN="LEFT" >+ navExE()</TD></TR>
<TR><TD ALIGN="LEFT" >+ runTgfestoModule()</TD></TR>
<TR><TD ALIGN="LEFT" >+ stopOlds(processName: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ stopProcesses()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    

    
}
@enduml